---
- name: Adding APT repository key
  apt_key: id={{ postgresql_apt_key_id }} url=https://www.postgresql.org/media/keys/{{ postgresql_apt_key_id}}.asc

- name: Add PostgreSQL official APT repository
  apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main"

- name: Update apt
  apt: update_cache=yes cache_valid_time=600 upgrade=full

- name: Install apt packages
  apt: pkg={{ item }} state=installed
  with_items: postgresql_apt_packages
