---
- name: Template copy; Configure nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: Template copy; Configure nginx host
  template: src=nginx.vhost.conf.j2  dest=/etc/nginx/sites-available/{{ nginx_sites_available[item].host }}
  with_items:
    - "{{ nginx_sites_enabled }}"
    
- name: Disable default
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Enable virtual host
  file: src=/etc/nginx/sites-available/{{ nginx_sites_available[item].host }} dest=/etc/nginx/sites-enabled/{{ nginx_sites_available[item].host }} state=link
  with_items:
    - "{{ nginx_sites_enabled }}"

- name: Reload nginx
  service: name=nginx state=reloaded