---
- name: Start Elasticsearch.
  service: 
    name: elasticsearch 
    state: started 
    enabled: yes

- name: Make sure Elasticsearch is running before proceeding.
  wait_for: 
    host: "{{ elasticsearch_network_host }}" 
    port: "{{ elasticsearch_http_port }}" 
    delay: 3 
    timeout: 300
