---
- name: Ensure unzip is installed.
  apt: 
    name: unzip 
    state: present

- name: Download and unarchive Packer.
  unarchive:
    src: https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: true
    creates: /usr/local/bin/packer

