# roles/ami/tasks/terminate.yml
---
- name: Output instance ids
  debug: var={{ ec2_fact.instance_ids }}

- name: Register new ami
  ec2_ami:
    aws_access_key={{ lookup('env','AWS_ACCESS_KEY_ID') }}
    aws_secret_key={{ lookup('env','AWS_SECRET_ACCESS_KEY') }}
    region={{ ami_aws_region }}
    instance_id={{ item }}
    wait=yes
    name="{{ ami_name }}-{{ ansible_date_time.epoch }}"
  with_items: ec2_fact.instance_ids

- name: Terminate instances that were previously launched
  ec2:
    state=absent
    instance_ids={{ item }}
    region={{ ami_aws_region }}
  with_items: ec2_fact.instance_ids
