---
- name: Add mysql5.6 repository.
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu trusty universe
    state: present
    update_cache: yes

- name: Install apt packages
  apt: 
    pkg: "{{ item }}" 
    state: present
  with_items:
    - python-mysqldb # needed for ansible module
    - "mysql-server-5.6"
    - "mysql-client-5.6"
