# Usage:
# vagrant up
# or:
# ansible-playbook workstation.yml
---
- name: Setup workstation
  hosts: all
  become: true

  vars:
    env: local
    # values to be used for ubuntu 14.04
    # php_major_version: 5
    # mysql_version: 5.6

  pre_tasks:
    - name: Update apt
      apt: 
        update_cache: yes 
        cache_valid_time: 600

  roles:
    - packer
    - boto
