---
common_apt_packages:
  - acl
  - git
  - vim
  - zip
  - mysql-client-5.6
  - curl
  - ntp
  - npm
  - build-essential
  - libssl-dev
  - libexpat1-dev
  - rsync
  - memcached
  - python-mysqldb
  - python-keyczar
  - python-setuptools
  - python-dev
  - python-pip

common_pip_packages:
  - ansible
  - jinja2
  - boto

common_npm_packages:
  - uglify-js
  - uglifycss
  - forever