---
- stat: path=/usr/local/bin/composer
  register: composer_installed
  tags:
    - install
    - composer
    - install:composer

- name: Install composer
  include_tasks: install.yml
  when: composer_installed.stat.exists == False
  tags:
    - install
    - composer
    - install:composer

- name: Configure composer
  include_tasks: configure.yml
  tags:
    - configure
    - composer
    - configure:composer