---
- name: Add repository
  apt_repository: 
    repo: ppa:brightbox/ruby-ng

- name: Install apt packages
  apt: 
    pkg: ruby2.3 
    state: installed

- name: Install pip awscli 
  command: pip install awscli

- name: Download s3 install
  get_url:
    url: https://aws-codedeploy-us-east-1.s3.amazonaws.com/latest/install
    dest: /tmp/install

- name: Add execute permission 
  file: 
    path: /tmp/install 
    mode: 0755

- name: Build aws cli
  command: "sudo /tmp/install auto"
  # [WARNING]: Consider using 'become', 'become_method', and 'become_user' rather than running sudo
  # tried the following and non of them work
  # become: true
  # become_method: sudo
  # become_user: root