---
- name: Update apt
  apt: update_cache=yes cache_valid_time=600 upgrade=full

- name: Install apt packages
  apt: pkg={{ item }} state=installed
  with_items:
    - python-pip
    - ruby2.0

- name: Install pip awscli 
  command: pip install awscli

- name: Download s3 install
  command: "aws s3 cp s3://aws-codedeploy-{{lookup('env','AWS_REGION')}}/latest/install /tmp --region {{lookup('env','AWS_REGION')}}"

- name: Add execute permission 
  command: "chmod +x /tmp/install"

- name: Build aws cli
  command: "/tmp/install auto"