---
- name: Create nodejs group
  shell: addgroup --system nodejs

- name: Create nodejs user
  shell: adduser --system --home /home/nodejs --shell /bin/bash --ingroup nodejs --gecos NodeJs,,, nodejs

- name: Template copy; Configure pm2
  copy: src=pm2 dest=/etc/init.d/pm2

- name: Permission upstart; Configure pm2
  command: chmod a+x /etc/init.d/pm2

- name: Update-rc.d; Configure pm2
  command: update-rc.d pm2 defaults