# Prod environment ansible variables
---
apache_sites_available:
  app:
    host: "{{app_domain_name}}"
    ports: [80, 443]
    directory_index: "app_{{env}}.php"
    document_root: /var/www/current/Symfony/web
    ssl:
      port: 443
      required: false
      engine_enabled: false
    directives:
      - 'Header set Access-Control-Allow-Origin "*"'
      - 'SetEnvIf Request_URI "/{{apache_health_check_file}}" is_heartbeat_request=1'
      - 'CustomLog /var/log/apache2/{{env}}.{{app_domain_name}}.log common env=!is_heartbeat_request'
  stc:
    host: "stc.{{app_domain_name}}"
    ports: [80, 443]
    directory_index: "app_{{env}}.php"
    document_root: /var/www/current/Symfony/web
    ssl:
      port: 443
      required: false
      engine_enabled: false
    directives:
      - 'FileETag none'
      - 'ExpiresActive On'
      - 'ExpiresDefault "access plus 1 year"'
      - 'Header set Access-Control-Allow-Origin "*"'
      - 'SetEnvIf Request_URI "/{{apache_health_check_file}}" is_heartbeat_request=1'
      - 'CustomLog /var/log/apache2/{{env}}-stc.{{app_domain_name}}.log common env=!is_heartbeat_request'

crontab_list:
  - "*/1 * * * * root php /var/www/current/Symfony/app/console JOB_COMMAND --env={{ env }}"