---
- name: Adding APT repository key
  apt_key: 
    id: "{{ postgresql_apt_key_id }}" 
    url: "https://www.postgresql.org/media/keys/{{ postgresql_apt_key_id}}.asc"

- name: Add PostgreSQL official APT repository
  apt_repository: 
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main"

- name: Install apt packages
  apt: 
    pkg: "{{ item }}"
    state: present
  with_items:
    - "postgresql-{{ postgresql_version }}"
    - python-psycopg2
    - libpq-dev

- name: Add postgis repo
  apt_repository:
    repo: ppa:ubuntugis/ubuntugis-unstable
    state: present

- name: Install postgresql-{{ postgresql_version }}-postgis-{{ postgis_version }}
  apt:
    pkg: postgresql-{{ postgresql_version }}-postgis-{{ postgis_version }}
    state: present

- name: List postgresql extension
  shell: psql -c "SELECT * FROM pg_extension;"
  args:
    executable: /bin/bash
  register: postgresql_plugin_list
  become: yes
  become_user: postgres
  become_method: sudo
  changed_when: False

- name: Create postgis extension
  shell: psql -c "CREATE EXTENSION IF NOT EXISTS postgis;"
  args:
    executable: /bin/bash
  become_user: postgres
  become_method: sudo