# Runs tasks that are for developer use only, running on local virtual machines
---
- name: Template copy; copy over updated bash prompt
  template:
    src: bash_prompt.j2
    dest: "{{ item }}/.bash_prompt"
  with_items:
    - "{{ bashprompt_paths }}"

- name: Update bashrc to load in our bash prompt
  lineinfile:
    dest: "{{ item }}/.bashrc"
    regexp: "^source .bash_prompt"
    state: present
    line: "source .bash_prompt"
  with_items:
    - "{{ bashprompt_paths }}"
