---
- name: Install apt packages
  apt: 
    pkg: "{{ item }}" 
    state: present
  with_items:
    - unzip
    - libwww-perl
    - libdatetime-perl

- name: Download CloudWatchMonitoringScripts
  unarchive:
    src: http://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.1.zip
    dest: /home/ubuntu
    remote_src: yes
    creates: /home/ubuntu/aws-scripts-mon
