---
- name: Composer update
  shell: composer self-update

- name: Composer install dependencies
  shell: composer install -d {{ site.deploy.src }} --prefer-dist --no-interaction --optimize-autoloader