---
- name: Download parameters.yml
  s3: bucket={{ site.deploy.parameters.s3.bucket }} object={{ site.deploy.parameters.s3.key }} dest={{ site.deploy.src }}/app/config/parameters.yml mode=get
  when: site.deploy.parameters is defined and site.deploy.parameters.s3 is defined