---
# php packages
- name: Install apt packages
  apt: 
    pkg: "{{ item }}" 
    state: present
  with_items:
    - "{{ php_package_prefix }}"
    - "{{ php_package_prefix }}-cli"
    - "{{ php_package_prefix }}-curl"
    - "{{ php_package_prefix }}-mysql"
    - "{{ php_package_prefix }}-intl"
    - "{{ php_package_prefix }}-gd"
    - "{{ php_package_prefix }}-mcrypt"
    - php-soap
    - php-pear
    - php-mbstring

# php 5 packages
- name: Install apt packages
  apt: 
    pkg: "{{ item }}" 
    state: present
  with_items:
    - php5-memcached
    - php5-redis
    - php-apc
  when: php_major_version == 5

# php 7 packages
- name: Install apt packages
  apt: 
    pkg: "{{ item }}" 
    state: present
  with_items:
    - php-memcached
    - php-redis
  when: php_major_version == 7

# apache2 configuration

- stat: 
    path: /usr/sbin/apache2
  register: apache2_installed

- debug: 
    msg: "apache2_installed: {{ apache2_installed }}"
  tags:
    - always
    
- name: Install mod php
  apt: 
    pkg: libapache2-mod-{{ php_package_prefix }} 
    state: installed
  when: apache2_installed.stat.exists == True

- stat: 
    path: /usr/sbin/a2enmod
  register: a2enmod_installed

- name: Enable mod php
  command: a2enmod {{ php_package_prefix }}
  when: a2enmod_installed.stat.exists == True