---
- name: start mysql server
  service: name=mysql state=started

- name: Create a new database if not exists
  mysql_db: name={{ app_database_name }} state=present

# - name: Update app database permission
#   mysql_user: name={{ app_database_user }} host={{ item }} password={{ app_database_password }} priv={{ app_database_name }}.*:ALL,GRANT
#   with_items:
#     - localhost
#   tags: mysql

- name: Update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

# This task is necessary for subsequent provisions after the initial root password
# update above. Later calls to update will fail without adding the cnf file.
- name: Template copy; root .my.cnf file with root password credentials
  template: src=root_my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: restart mysql server
  service: name=mysql state=restarted
