---
- name: Install common apt packages
  apt: 
    pkg:
      - acl
      - vim
      - zip
      - curl
      - ntp
      - rsync
      - jq
      - wget
      - sudo
      - awscli
    state: present
