# This script runs on it's own. It's used to generate AMI images with
# whatever software is necessary already pre-installed.
#
# Note 1: you will need to declare the aws access key and aws secret key, which is different per project.
# Easiest way is to export them as environment variables.
# See here: http://docs.ansible.com/intro_dynamic_inventory.html#example-aws-ec2-external-inventory-script
#
# For more information about Ansible and aws, see here: http://docs.ansible.com/guide_aws.html
#
# Note 2: you will probably need to run this script with your ec2.ini destination variables set to public ips.
#
# export AWS_ACCESS_KEY_ID='XXXX'
# export AWS_SECRET_ACCESS_KEY='XXXX'
# export EC2_OVERRIDE_DESTVAR='public'
# Usage:
# ansible-playbook -i /etc/ansible/plugins/inventory/ec2.py --user=ubuntu --private-key=~/path/yourkey.pem ami.yml
---
- name: Create an instance
  hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - { role: ami, action: 'launch' }

- name: Provision an instance
  hosts: launched
  user: ubuntu
  sudo: true
  gather_facts: true
  vars:
    ami: true
  roles:
    - common
    - { role: ami, action: 'configure' }
  tasks:
    - name: Set init services to manual start
      shell: echo manual | sudo tee /etc/init/{{ item }}.override
      with_items:
        - mysql
    - name: Set update-rc.d services to start manually
      command: sudo update-rc.d -f {{ item }} remove
      with_items:
        - apache2
        - memcached

- name: Create an AMI and Terminate instance
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - { role: ami, action: 'terminate' }
