---
- name: Setup workstation
  hosts: localhost
  connection: local
  become: true

  vars_files:
    - group_vars/local.yml

  pre_tasks:
    - name: Update apt
      apt: update_cache=yes cache_valid_time=600

  roles:
    - common
    - memcached
    - mysql
    - nodejs
    - php
    - composer
    - { role: apache, apache_sites_enabled: ['app', 'stc'] }