---
- name: Add PHP elasticache.ini
  template: src=elasticache.ini.j2 dest={{ php_mods_path }}/elasticache.ini

- name: Enable the elasticache.ini
  command: php5enmod elasticache

- name: Disable memcached
  command: php5dismod memcached