---
- name: Composer update
  shell: composer self-update

- name: Composer install dependencies
  shell: composer install -d {{ symfony2_deploy_src }} --prefer-dist --no-interaction --optimize-autoloader