---
- name: Permission release directory
  file: path={{ site.deploy.src }} owner=ubuntu group=ubuntu state=directory recurse=yes

- name: Remove ignore files
  file: dest={{ site.deploy.src }}/{{ item }} state=absent
  with_items:
    - "{{ site.deploy.ignore }}"
  when: site.deploy.ignore is defined

- name: Create app/cache app/logs
  file: dest={{ item }} state=directory owner=ubuntu group=ubuntu
  with_items:
    - "{{ site.deploy.src }}/app/cache"
    - "{{ site.deploy.src }}/app/logs"

- name: Set app/cache app/logs permissions
  command: setfacl -R -m u:www-data:rwX -m u:ubuntu:rwX {{ item }} & setfacl -dR -m u:www-data:rwX -m u:ubuntu:rwX {{ item }}
  with_items:
    - "{{ site.deploy.src }}/app/cache"
    - "{{ site.deploy.src }}/app/logs"

- name: Warm up cache
  # this also warms up the cache
  command: php {{ site.deploy.src }}/app/console cache:clear --env={{ env }} --no-debug

- name: Set deploy_dest
  command: dirname {{ site.deploy.dest }}
  register: deploy_dest
  ignore_errors: yes

- name: Set deploy_dest variable
  set_fact: deploy_dest={{ deploy_dest.stdout }}

- name: Create destination directory
  file: path={{ deploy_dest }} state=directory owner=ubuntu group=ubuntu

- name: Create symlink
  file: dest={{ site.deploy.dest }} src={{ site.deploy.src }} state=link
