---
- name: Download parameters
  include: parameters.yml
  tags:
    - symfony2
    - parameters
    - deploy

- name: Composer update
  include: composer.yml
  tags:
    - symfony2
    - dependencies
    - deploy

- name: Migrate symfony2
  include: migrate.yml
  tags:
    - symfony2
    - migrate
    - deploy

- name: Release symfony2
  include: release.yml
  tags:
    - symfony2
    - release
    - deploy