---
- name: Download parameters
  include: parameters.yml
  tags:
    - parameters
    - symfony2
    - parameters:symfony2

- name: Composer update
  include: composer.yml
  tags:
    - dependencies
    - symfony2
    - dependencies:symfony2

- name: Migrate symfony2
  include: migrate.yml
  tags:
    - migrate
    - symfony2
    - migrate:symfony2

- name: Deploy symfony2
  include: deploy.yml
  tags:
    - deploy
    - symfony2
    - deploy:symfony2