---
- name: Symfony2 site
  debug: var=site
  tags:
    - always

- name: Download parameters
  include_tasks: parameters.yml
  tags:
    - parameters
    - symfony2
    - parameters:symfony2

- name: Composer update
  include_tasks: composer.yml
  tags:
    - dependencies
    - symfony2
    - dependencies:symfony2

- name: Migrate symfony2
  include_tasks: migrate.yml
  tags:
    - migrate
    - symfony2
    - migrate:symfony2

- name: Deploy symfony2
  include_tasks: deploy.yml
  tags:
    - deploy
    - symfony2
    - deploy:symfony2