# roles/ami/tasks/launch.yml
---
- name: Launch Instance
  ec2:
    keypair={{ ami_keypair }}
    group={{ ami_security_group }}
    instance_type={{ ami_instance_type }}
    image={{ ami_base_image }}
    region={{ ami_aws_region }}
    vpc_subnet_id={{ ami_vpc_subnet }}
    assign_public_ip=true
    instance_tags='{"Name":"ami-{{ ansible_date_time.epoch }}"}'
    count=1
    wait=true
  register: ec2

- name: Add new instance to host group
  add_host: hostname={{ item.public_ip }} groupname=launched
  with_items: 
    - "{{ ec2.instances }}"

- name: Wait for SSH to come up
  wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=320 state=started
  with_items:
    - "{{ ec2.instances }}"

- set_fact:
    ec2_fact: "{{ ec2 }}"
