# This script is used to install the core set of software
# that's used by all machines, for all environments
---
# - name: Add apt repositories
#   apt_repository: repo={{ item }}
#   with_items: packages_apt_repositories
#   when: packages_apt_repositories is defined

- name: Update apt
  apt: update_cache=yes cache_valid_time=600 upgrade=full

- name: Install apt packages
  apt: pkg={{ item.name }} state=installed
  with_items: common_packages
  when: item.manager == 'apt'

- name: Update pip 
  command: pip install -U pip

- name: Install pip packages
  pip: name={{ item.name }} state=latest
  with_items: common_packages
  when: item.manager == 'pip'

- name: Install npm packages
  npm: name={{ item.name }} global=yes
  with_items: common_packages
  when: item.manager == 'npm'