---
- name: Install apt packages
  apt: pkg={{ item }} state=installed
  with_items:
    - php5
    - php-apc
    - php-soap
    - php-pear
    - php5-cli
    - php5-curl
    - php5-mysql
    - php5-intl
    - php5-gd
    - php5-mcrypt
    - php5-memcached
    - php5-redis