# Deploys code to servers (e.g. to dev or prod)
---
- hosts: "&{{ env | expand('tag_Env_') }}:{{ roles | expand('tag_Roles_') }}"
  sudo: True
  #accelerate: true
  vars_files:
    - group_vars/{{ env }}.yml
  vars:
    release_dir_prefix: /var/www
    release_dir_parent: releases
    parameters_dir: Symfony/app/config

  tasks:

    - name: Set release_dir variable path
      set_fact: release_dir="{{ release_dir_prefix }}/{{ release_dir_parent }}/{{ build_id }}"

    - name: Create release directory
      file: dest={{ release_dir }} mode=755 owner=ubuntu group=ubuntu state=directory

    - name: Rsync
      synchronize: src=../../ dest={{release_dir}} delete=yes rsync_opts="--exclude-from=../rsync_exclude_{{ env }}"
      #http://programmersnotebook.wordpress.com/2010/03/20/rsync-and-exclude-from/

    - name: Permission release directory
      file: path={{ release_dir }} owner=ubuntu group=ubuntu state=directory recurse=yes

    - name: Create app/cache app/logs
      file: dest={{ item }} state=directory owner=www-data group=www-data
      with_items:
        - "{{ release_dir }}/Symfony/app/cache"
        - "{{ release_dir }}/Symfony/app/logs"

    - name: Set app/cache app/logs permissions
      command: setfacl -R -m u:www-data:rwX -m u:ubuntu:rwX {{ item }} & setfacl -dR -m u:www-data:rwX -m u:ubuntu:rwX {{ item }}
      with_items:
        - "{{ release_dir }}/Symfony/app/cache"
        - "{{ release_dir }}/Symfony/app/logs"

    - name: Copy credentials
      command: "cp /home/ubuntu/.parameters.yml {{ release_dir }}/{{ parameters_dir }}/parameters.yml"

    - name: Set credentials permissions
      file:
        path: "{{ release_dir }}/{{ parameters_dir }}/parameters.yml"
        owner: root
        group: root
        mode: 0400

    - name: Warm up cache
      remote_user: ubuntu
      command: php {{ release_dir }}/Symfony/app/console cache:clear --env={{ env }} --no-debug

    - name: Create symlink
      file: dest={{ app_dir_root }} src={{ release_dir }} state=link

    - name: Delete all previous release, except the one we just created
      shell: "find '{{ release_dir_prefix }}/{{ release_dir_parent }}' -maxdepth 1 ! -name '{{ release_dir_parent }}' ! -name '{{ build_id }}' | xargs rm -rf"
