---
- name: Install apt packages
  apt: 
    pkg:
      - python-mysqldb # needed for ansible module
      - "mysql-server-{{ mysql_version }}"
      - "mysql-client-{{ mysql_version }}"
    state: present