---
- name: Ensure the PGP key is installed for passenger
  apt_key: 
    id: AC40B2F7 
    state: present 
    url: "http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x561F9B9CAC40B2F7"

- name: Add apt repositories
  apt_repository: 
    state: present 
    repo: "deb https://oss-binaries.phusionpassenger.com/apt/passenger trusty main"

- name: Install apt packages
  apt: 
    pkg: "{{ item }}"
    state: present
  with_items:
    - nginx-full
    - passenger