---
- name: Add repository
  apt_repository: repo='ppa:brightbox/ruby-ng'

- name: Install apt packages
  apt: pkg={{ item }} state=installed
  with_items:
    - "ruby{{ ruby_version }}"
    # Rails installation dependencies
    - "ruby{{ ruby_version }}-dev"
    - zlib1g-dev
