---
- name: Install apt packages
  apt: pkg={{ item }} state=installed
  with_items:
    - curl
    - zlib1g-dev
    - build-essential
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - libxslt1-dev
    - libcurl4-openssl-dev
    - python-software-properties
    - libffi-dev
    - libmysqlclient-dev # needed for mysql gem

- name: Set release_dir variable path
  set_fact: ruby_build_dir=/tmp/ruby-{{ ruby_version }}

- name: Download ruby
  get_url: url=http://ftp.ruby-lang.org/pub/ruby/ruby-{{ ruby_version }}.tar.gz dest=/tmp/ruby-{{ ruby_version }}.tar.gz

- name: Unarchive ruby
  command: tar -xzvf /tmp/ruby-{{ ruby_version }}.tar.gz -C /tmp

- name: Configure ruby
  command: './configure chdir={{ ruby_build_dir }}'

- name: Make ruby
  command: 'make chdir={{ ruby_build_dir }}'

- name: Make ruby install
  command: 'make install chdir={{ ruby_build_dir }}'

- name: Update gemrc
  lineinfile: 'dest={{ ruby_home }}/.gemrc create=yes line="gem: --no-ri --no-rdoc" insertafter=EOF'