---
- name: Install common apt packages
  apt: 
    pkg: "{{ item }}"
    state: present
  with_items:
    - acl
    - vim
    - zip
    - curl
    - ntp
    - rsync
    - jq
    - wget
    - sudo
    - build-essential
    - libssl-dev
    - locales