---
- name: Install common apt packages
  apt: 
    pkg: "{{ item }}"
    state: present
  with_items:
    - acl
    - vim
    - zip
    - unzip
    - curl
    - ntp
    - rsync
    - jq
    - wget
    - sudo
    - build-essential
    - libssl-dev
    - locales
    - python3.6-dev

- name: Setup locale
  shell: |
    locale-gen en_US.UTF-8
    locale-gen --no-purge --lang en_US.UTF-8